# fly.toml app configuration file generated for payments-app-api on 2023-08-28T12:10:27+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "payments-app-api"
primary_region = "jnb"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
